packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
catalogMode: prefer

catalogs:
  build:
    '@tsdown/css': ^0.22.11
    esbuild: ^0.28.1
    fflate: ^0.8.3
    pathe: ^2.0.3
    tinyglobby: ^0.2.17
  capacitor:
    '@capacitor/android': ^8.4.2
    '@capacitor/app': ^8.1.1
    '@capacitor/cli': ^8.4.2
    '@capacitor/core': ^8.4.2
    '@capacitor/docgen': ^0.3.1
    '@capacitor/filesystem': ^8.1.2
    '@capacitor/ios': ^8.4.2
    xmlbuilder: ^15.1.1
  cli:
    '@inquirer/prompts': ^8.5.2
    consola: ^3.4.2
    esno: ^4.8.0
    unconfig: ^7.5.0
  electron:
    bonjour-service: ^1.4.3
    electron: ^41.2.0
    electron-builder: ^26.15.3
    importx: ^0.5.2
    tar: ^7.5.20
  release:
    bumpp: ^11.1.0
  style:
    sass: ^1.101.0
    uno-colors: ^0.1.0
  types:
    '@types/node': ^26.1.1
    '@typescript/native-preview': 7.0.0-dev.20260328.1
    typescript: ^7.0.2
  unocss:
    '@unocss/config': ^66.7.5
    '@unocss/preset-attributify': ^66.7.5
    '@unocss/preset-icons': ^66.7.5
    '@unocss/preset-typography': ^66.7.5
    '@unocss/preset-web-fonts': ^66.7.5
    '@unocss/preset-wind3': ^66.7.5
    '@unocss/reset': ^66.7.5
    '@unocss/vite': ^66.7.5
    unocss: ^66.7.5
  vite:
    '@vitejs/plugin-vue': ^6.0.8
    unplugin-auto-import: ^21.0.0
    unplugin-vue: ^7.2.0
    unplugin-vue-components: ^32.1.0
    vite: npm:@voidzero-dev/vite-plus-core@0.1.16
    vite-plus: ^0.2.5
    vitest: npm:@voidzero-dev/vite-plus-test@0.1.16
    vue-tsc: ^3.3.7
  vue:
    vue: ^3.5.40
    vue-router: ^5.2.0
overrides:
  vite: 'catalog:vite'
  vitest: 'catalog:vite'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'

packageExtensions:
  plist:
    dependencies:
      xmlbuilder: ^15.1.1
