import { mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

export function resolveRepositoryRoot(fromImportMetaUrl: string): string {
  const currentFileDir = dirname(fileURLToPath(fromImportMetaUrl));
  return resolve(currentFileDir, "../..");
}

export function resolveAutoGeneratedDir(fromImportMetaUrl: string): string {
  return resolve(resolveRepositoryRoot(fromImportMetaUrl), ".auto-generated");
}

export async function ensureAutoGeneratedDir(fromImportMetaUrl: string): Promise<string> {
  const autoGeneratedDir = resolveAutoGeneratedDir(fromImportMetaUrl);
  await mkdir(autoGeneratedDir, { recursive: true });
  return autoGeneratedDir;
}
