/**
 * Re-export shim for the canonical bridge wire schema.
 *
 * The actual definitions live in `@synra/bridge-schema` (a leaf package
 * with no runtime dependencies on plugin-sdk / plugin-system). We
 * re-export here so existing internal imports
 * (`from '../shared/protocol/types'`) keep working without churn and
 * the public API surface (`@synra/capacitor-electron`) stays stable.
 */
export type {
  BridgeErrorResponse,
  BridgeMethod,
  BridgeRequest,
  BridgeRequestMeta,
  BridgeResponse,
  BridgeSuccessResponse,
  MethodPayloadMap,
  MethodResultMap,
  OpenExternalOptions,
  DiscoveryMode,
  DiscoverySource,
  DiscoveryState,
  DiscoveredDevice,
  DeviceDiscoveryListResult,
  DeviceTransportOpenOptions,
  DeviceTransportOpenResult,
  SynraLanConnectType,
  ConnectionTransport,
  DeviceTransportCloseOptions,
  DeviceTransportCloseResult,
  DeviceTransportSendMessageOptions,
  DeviceTransportSendMessageResult,
  DeviceTransportSendLanEventOptions,
  DeviceTransportSendLanEventResult,
  DeviceTransportGetStateOptions,
  DeviceTransportSnapshot,
  DeviceDiscoveryStartOptions,
  DeviceDiscoveryStartResult,
  DeviceDiscoveryHostEvent,
  PluginCatalogResult,
  PluginInstallOptions,
  PluginInstallLocalOptions,
  PluginInstallResult,
  PluginListInstalledOptions,
  PluginListInstalledResult,
  PluginRegisterInstalledOptions,
  PluginRegisterInstalledResult,
  PluginSyncToDeviceOptions,
  PluginSyncToDeviceResult,
  PluginUninstallOptions,
  PluginUninstallResult,
  InstalledPluginSummary,
  OperationResult,
  ReadClipboardResult,
  ReadFileOptions,
  ReadFileResult,
  ResolveRuntimeActionsOptions,
  WriteClipboardOptions,
  ResolveRuntimeActionsResult,
  RuntimeActionCandidate,
  RuntimeExecuteOptions,
  RuntimeExecuteResult,
  RuntimeInfo,
  PluginRegisterFailure,
  PluginRegisterFailureReason,
  AppListInstalledOptions,
  AppListInstalledResult,
  AppLaunchOptions,
  AppLaunchResult,
  InstalledApp
} from '@synra/bridge-schema'
