import { spawn } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { select } from '@inquirer/prompts'
import { ensureAutoGeneratedDir } from '../common/utils.ts'

const VP_COMMAND = 'vp'
const BUILD_HISTORY_FILE = 'build-history.json'
const MAX_HISTORY_ITEMS = 3

const BUILD_TARGETS = ['frontend', 'windows', 'linux', 'macos', 'android', 'ios', 'all'] as const
type BuildTarget = (typeof BUILD_TARGETS)[number]

type BuildHistory = {
  recentTargets: BuildTarget[]
}

type BuildStep = {
  title: string
  command: string
  args: string[]
  env?: NodeJS.ProcessEnv
}

const buildToolsStep: BuildStep = {
  title: 'Build tools/packages',
  command: VP_COMMAND,
  args: ['run', 'build:tools'],
  env: process.platform === 'win32' ? { VP_RUN_CONCURRENCY_LIMIT: '1' } : undefined
}

const stepsByTarget: Record<BuildTarget, BuildStep[]> = {
  frontend: [
    buildToolsStep,
    {
      title: 'Build frontend',
      command: VP_COMMAND,
      args: ['run', 'frontend#build']
    }
  ],
  windows: [
    {
      title: 'Package installer (Windows)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:windows'],
      env: {
        CSC_IDENTITY_AUTO_DISCOVERY: 'false'
      }
    }
  ],
  linux: [
    {
      title: 'Package installer (Linux)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:linux']
    }
  ],
  macos: [
    {
      title: 'Package installer (macOS)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:macos']
    }
  ],
  android: [
    buildToolsStep,
    {
      title: 'Build frontend for mobile',
      command: VP_COMMAND,
      args: ['run', 'frontend#build']
    },
    {
      title: 'Sync Android project',
      command: VP_COMMAND,
      args: ['run', 'mobile#sync:android']
    }
  ],
  ios: [
    buildToolsStep,
    {
      title: 'Build frontend for mobile',
      command: VP_COMMAND,
      args: ['run', 'frontend#build']
    },
    {
      title: 'Sync iOS project',
      command: VP_COMMAND,
      args: ['run', 'mobile#sync:ios']
    }
  ],
  all: [
    buildToolsStep,
    {
      title: 'Build frontend',
      command: VP_COMMAND,
      args: ['run', 'frontend#build']
    },
    {
      title: 'Package installer (Windows)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:windows']
    },
    {
      title: 'Package installer (Linux)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:linux']
    },
    {
      title: 'Package installer (macOS)',
      command: VP_COMMAND,
      args: ['run', 'electron#package:macos']
    },
    {
      title: 'Sync Android project',
      command: VP_COMMAND,
      args: ['run', 'mobile#sync:android']
    },
    {
      title: 'Sync iOS project',
      command: VP_COMMAND,
      args: ['run', 'mobile#sync:ios']
    }
  ]
}

function isBuildTarget(value: string): value is BuildTarget {
  return (BUILD_TARGETS as readonly string[]).includes(value)
}

async function runStep(step: BuildStep): Promise<void> {
  await new Promise<void>((resolveStep, rejectStep) => {
    const child =
      process.platform === 'win32'
        ? spawn(`${step.command} ${step.args.join(' ')}`, {
            stdio: 'inherit',
            shell: true,
            env: {
              ...process.env,
              ...step.env
            }
          })
        : spawn(step.command, step.args, {
            stdio: 'inherit',
            env: {
              ...process.env,
              ...step.env
            }
          })

    child.on('error', (error) => {
      rejectStep(error)
    })

    child.on('close', (code) => {
      if (code === 0) {
        resolveStep()
        return
      }

      rejectStep(
        new Error(
          `Command failed: ${step.command} ${step.args.join(' ')} (exit code ${code ?? 'null'})`
        )
      )
    })
  })
}

async function runBuildTarget(target: BuildTarget): Promise<void> {
  const steps = stepsByTarget[target]
  for (const step of steps) {
    console.log(`\n==> ${step.title}`)
    await runStep(step)
  }
}

function normalizeHistory(values: unknown): BuildTarget[] {
  if (!Array.isArray(values)) {
    return []
  }

  return values
    .filter((value): value is BuildTarget => typeof value === 'string' && isBuildTarget(value))
    .slice(0, MAX_HISTORY_ITEMS)
}

async function readHistory(historyFilePath: string): Promise<BuildTarget[]> {
  try {
    const raw = await readFile(historyFilePath, 'utf8')
    const parsed = JSON.parse(raw) as Partial<BuildHistory>
    return normalizeHistory(parsed.recentTargets)
  } catch {
    return []
  }
}

async function writeHistory(historyFilePath: string, recentTargets: BuildTarget[]): Promise<void> {
  const payload: BuildHistory = {
    recentTargets: normalizeHistory(recentTargets)
  }
  await writeFile(historyFilePath, `${JSON.stringify(payload, null, 2)}\n`, 'utf8')
}

function bumpHistory(currentHistory: BuildTarget[], target: BuildTarget): BuildTarget[] {
  return [target, ...currentHistory.filter((item) => item !== target)].slice(0, MAX_HISTORY_ITEMS)
}

function buildChoices(history: BuildTarget[]): Array<{ name: string; value: BuildTarget }> {
  const choices: Array<{ name: string; value: BuildTarget }> = []

  for (const target of history) {
    choices.push({
      name: `Recent: ${target}`,
      value: target
    })
  }

  for (const target of BUILD_TARGETS) {
    if (history.includes(target)) {
      continue
    }

    choices.push({
      name: target,
      value: target
    })
  }

  return choices
}

async function resolveBuildTarget(history: BuildTarget[]): Promise<BuildTarget> {
  const fromArg = process.argv[2]?.trim().toLowerCase()
  if (fromArg) {
    if (!isBuildTarget(fromArg)) {
      throw new Error(
        `Invalid build target argument: ${fromArg}. Expected one of: ${BUILD_TARGETS.join(', ')}.`
      )
    }
    return fromArg
  }

  const fromEnv = process.env.BUILD_TARGET?.trim().toLowerCase()
  if (fromEnv) {
    if (!isBuildTarget(fromEnv)) {
      throw new Error(
        `Invalid BUILD_TARGET: ${fromEnv}. Expected one of: ${BUILD_TARGETS.join(', ')}.`
      )
    }
    return fromEnv
  }

  return select({
    message: 'Select build target',
    choices: buildChoices(history),
    pageSize: 10
  })
}

const autoGeneratedDir = await ensureAutoGeneratedDir(import.meta.url)
const historyFilePath = resolve(autoGeneratedDir, BUILD_HISTORY_FILE)
const currentHistory = await readHistory(historyFilePath)

const target = await resolveBuildTarget(currentHistory)
console.log(`\nSelected build target: ${target}`)

await runBuildTarget(target)

const nextHistory = bumpHistory(currentHistory, target)
await writeHistory(historyFilePath, nextHistory)

console.log('\nBuild flow completed.')
