/**
 * v3 plugin contract — keep every Vue public API alive in the host
 * build's tree-shake pass.
 *
 * The plugin SDK tells plugin bundles to keep `vue` external (so the
 * plugin and host share one Vue runtime via importmap). Plugin bundles
 * compiled from `.vue` SFCs import Vue compiler helpers by their public
 * names — `createElementVNode`, `createElementBlock`, `Transition`,
 * etc. — which the importmap resolves to the host's `vendor-vue` chunk.
 *
 * `vue` is published as a thin ESM stub that does `export * from
 * '@vue/runtime-dom'`. The `@vue/runtime-dom` build itself only
 * exposes `createBaseVNode as createElementVNode` and the runtime-dom
 * helpers (`Transition`, `withKeys`, `withModifiers`, ...). When the
 * host tree-shakes its build, Rollup drops any name the host's own
 * code never references — so the `vendor-vue` chunk ends up exporting
 * `createElementBlock` but not `createElementVNode`, and `Transition`
 * is missing entirely. When the chat plugin then mounts on Android,
 * its compiled render function calls `createElementVNode(...)` against
 * `undefined`, the patch path bails, and Vue's `setRef` reads
 * `null.refs` — surface error
 * `TypeError: Cannot read properties of null (reading 'refs')`.
 *
 * This file re-exports the full public Vue surface as named bindings.
 * A bare `export { Transition } from '@vue/runtime-dom'` is NOT
 * sufficient — Rollup tree-shake would see that nothing in the host
 * graph uses `Transition` and inline the symbol into use sites instead
 * of emitting a live `export { Transition }` in the vendor-vue chunk.
 * To force a live binding we additionally publish every name onto
 * `globalThis.__SYNRA_VUE_PUBLIC_API__` — a side effect that any
 * tree-shaker has to honor. The map is also handy for debugging which
 * Vue helpers the plugin runtime expects.
 */
import {
  Fragment,
  Teleport,
  Transition,
  TransitionGroup,
  computed,
  createBlock,
  createCommentVNode,
  createElementBlock,
  createTextVNode,
  createVNode,
  defineComponent,
  defineAsyncComponent,
  defineCustomElement,
  defineModel,
  defineProps,
  defineEmits,
  defineExpose,
  defineOptions,
  defineSlots,
  createApp,
  createSSRApp,
  render,
  hydrate,
  h,
  ref,
  shallowRef,
  reactive,
  shallowReactive,
  readonly,
  shallowReadonly,
  effectScope,
  customRef,
  triggerRef,
  proxyRefs,
  toRefs,
  toRef,
  toRaw,
  toValue,
  isRef,
  isReactive,
  isReadonly,
  isProxy,
  isShallow,
  markRaw,
  unref,
  stop,
  watch,
  useModel,
  useTemplateRef,
  inject,
  provide,
  nextTick,
  onActivated,
  onBeforeMount,
  onBeforeUpdate,
  onBeforeUnmount,
  onDeactivated,
  onErrorCaptured,
  onMounted,
  onRenderTracked,
  onRenderTriggered,
  onServerPrefetch,
  onUnmounted,
  onUpdated,
  onScopeDispose,
  getCurrentInstance,
  getCurrentScope,
  hasInjectionContext,
  useAttrs,
  useId,
  useSlots,
  useSSRContext,
  useTransitionState,
  Text,
  Comment,
  Static,
  BaseTransition,
  KeepAlive,
  Suspense,
  openBlock,
  cloneVNode,
  mergeProps,
  normalizeClass,
  normalizeStyle,
  resolveComponent,
  resolveDirective,
  resolveDynamicComponent,
  renderList,
  renderSlot,
  toDisplayString,
  withCtx,
  withDirectives,
  withKeys,
  withModifiers,
  vModelText,
  vModelCheckbox,
  vModelRadio,
  vModelSelect,
  vModelDynamic,
  vShow,
  version,
  warn,
  withDefaults,
  withMemo,
  withScopeId,
  initCustomFormatter
} from 'vue'

// `mergeModels` lives in `@vue/runtime-core`. It is part of the public
// runtime API (compiled `.vue` SFCs reference it directly), but Vue's
// own `.d.ts` does not declare it (it expects apps to use
// `defineModel` instead). Ignore the missing-type error so rollup can
// still resolve it through the runtime export.
// @ts-ignore -- runtime export not declared in @vue/runtime-core/dist/runtime-core.d.ts
import { mergeModels } from '@vue/runtime-core'

// Force a live `createElementVNode` binding in the vendor-vue chunk's
// export block. `createElementVNode` is implemented in
// `@vue/runtime-core` as `createBaseVNode` and exported via the
// `createBaseVNode as createElementVNode` alias. When we `import {
// createElementVNode } from '@vue/runtime-core'` and then `export {
// createElementVNode }` from this file, Rollup traces the alias back
// to `createBaseVNode` and emits `Os as createBaseVNode` in the chunk
// instead of `Os as createElementVNode` — the plugin bundle's
// `import { createElementVNode } from 'vue'` then resolves to
// `undefined`. A standalone `export ... from` statement preserves
// the source's public name through to the chunk's export block.
export { createElementVNode } from '@vue/runtime-core'

// Side-effect binding — keep every name as a live, surviving-the-tree-shake
// export. We assign into globalThis so the bundle cannot drop the
// references. Doing this also makes a `__SYNRA_VUE_PUBLIC_API__` debug
// map available in DevTools for verifying which Vue helpers the host's
// plugin runtime expects.
const __SYNRA_VUE_PUBLIC_API__ = {
  Fragment,
  Teleport,
  Transition,
  TransitionGroup,
  computed,
  createBlock,
  createCommentVNode,
  createElementBlock,
  createTextVNode,
  createVNode,
  defineComponent,
  defineAsyncComponent,
  defineCustomElement,
  defineModel,
  defineProps,
  defineEmits,
  defineExpose,
  defineOptions,
  defineSlots,
  createApp,
  createSSRApp,
  render,
  hydrate,
  h,
  ref,
  shallowRef,
  reactive,
  shallowReactive,
  readonly,
  shallowReadonly,
  effectScope,
  customRef,
  triggerRef,
  proxyRefs,
  toRefs,
  toRef,
  toRaw,
  toValue,
  isRef,
  isReactive,
  isReadonly,
  isProxy,
  isShallow,
  markRaw,
  unref,
  stop,
  watch,
  useModel,
  useTemplateRef,
  inject,
  provide,
  nextTick,
  onActivated,
  onBeforeMount,
  onBeforeUpdate,
  onBeforeUnmount,
  onDeactivated,
  onErrorCaptured,
  onMounted,
  onRenderTracked,
  onRenderTriggered,
  onServerPrefetch,
  onUnmounted,
  onUpdated,
  onScopeDispose,
  getCurrentInstance,
  getCurrentScope,
  hasInjectionContext,
  useAttrs,
  useId,
  useSlots,
  useSSRContext,
  useTransitionState,
  Text,
  Comment,
  Static,
  BaseTransition,
  KeepAlive,
  Suspense,
  openBlock,
  cloneVNode,
  mergeProps,
  normalizeClass,
  normalizeStyle,
  resolveComponent,
  resolveDirective,
  resolveDynamicComponent,
  renderList,
  renderSlot,
  toDisplayString,
  withCtx,
  withDirectives,
  withKeys,
  withModifiers,
  vModelText,
  vModelCheckbox,
  vModelRadio,
  vModelSelect,
  vModelDynamic,
  vShow,
  version,
  warn,
  withDefaults,
  withMemo,
  withScopeId,
  initCustomFormatter,
  mergeModels
}

if (typeof globalThis !== 'undefined') {
  ;(globalThis as unknown as { __SYNRA_VUE_PUBLIC_API__?: unknown }).__SYNRA_VUE_PUBLIC_API__ =
    __SYNRA_VUE_PUBLIC_API__
}

// Re-export each name so other host code can `import { Transition,
// createElementVNode, ... } from '@/plugins/host/synra-vue-reexport'`
// and tree-shake the unused ones locally without losing the vendor-vue
// chunk binding. `createElementVNode` is exposed via the standalone
// re-export above and `mergeModels` is exported separately below.
export {
  Fragment,
  Teleport,
  Transition,
  TransitionGroup,
  computed,
  createBlock,
  createCommentVNode,
  createElementBlock,
  createTextVNode,
  createVNode,
  defineComponent,
  defineAsyncComponent,
  defineCustomElement,
  defineModel,
  defineProps,
  defineEmits,
  defineExpose,
  defineOptions,
  defineSlots,
  createApp,
  createSSRApp,
  render,
  hydrate,
  h,
  ref,
  shallowRef,
  reactive,
  shallowReactive,
  readonly,
  shallowReadonly,
  effectScope,
  customRef,
  triggerRef,
  proxyRefs,
  toRefs,
  toRef,
  toRaw,
  toValue,
  isRef,
  isReactive,
  isReadonly,
  isProxy,
  isShallow,
  markRaw,
  unref,
  stop,
  watch,
  useModel,
  useTemplateRef,
  inject,
  provide,
  nextTick,
  onActivated,
  onBeforeMount,
  onBeforeUpdate,
  onBeforeUnmount,
  onDeactivated,
  onErrorCaptured,
  onMounted,
  onRenderTracked,
  onRenderTriggered,
  onServerPrefetch,
  onUnmounted,
  onUpdated,
  onScopeDispose,
  getCurrentInstance,
  getCurrentScope,
  hasInjectionContext,
  useAttrs,
  useId,
  useSlots,
  useSSRContext,
  useTransitionState,
  Text,
  Comment,
  Static,
  BaseTransition,
  KeepAlive,
  Suspense,
  openBlock,
  cloneVNode,
  mergeProps,
  normalizeClass,
  normalizeStyle,
  resolveComponent,
  resolveDirective,
  resolveDynamicComponent,
  renderList,
  renderSlot,
  toDisplayString,
  withCtx,
  withDirectives,
  withKeys,
  withModifiers,
  vModelText,
  vModelCheckbox,
  vModelRadio,
  vModelSelect,
  vModelDynamic,
  vShow,
  version,
  warn,
  withDefaults,
  withMemo,
  withScopeId,
  initCustomFormatter,
  mergeModels
}
